### ISSUE TITLE
Not possible to control color on Luna lamp

### ISSUE THREAD

**Issue by kennidenni** [NamronAS/Namron_Homey#98]
The light is really cold by default and it should support changing color as it is possible if it is connected to a Philips Hue hub first.

**Comment by Roaldoien** [comment]
Previous case was closed after last version. Still not providing the color change option. It was there before, so I cant really understand what the problem is. @prj84 Can you explain?

**Comment by prj84** [comment]
We have pushed the diveloper for a fix

**Comment by silentclove** [comment]
I have homey 2019, still can't adjust light temperatur. It's really bright white! Is the update 2.2.77 just for homey 2023?

**Comment by prj84** [comment]
Last ned test versjonen av Namron appen som skal fikse dette problemet. Pass på å inkludere enheten på nytt for at alt skal fungere. https://homey.app/no-no/app/net.filllip-namron/Namron/test/
